### DISCUSSION TITLE
How to stop "Problems" in notebooks from being detected/shown to the user prior to running the code?

### DISCUSSION THREAD

**Discussion by kostrykin** [microsoft/vscode-jupyter#14840] [Questions and Answers]
I'm preparing a training course, which will involve Python and Jupyter Notebooks. For this course, it is important that code errors are only shown to the user when the code is executed, so Linters should be disabled. I figured out how to disable Linters (Pylance),
```yml
    "vscode": {
      "extensions": [
        "ms-toolsai.jupyter"
      ],
      "settings": {
        "python.linting.enabled": false,
        "python.linting.pylintEnabled": false,
        "python.languageServer": "None"
      }
    }
```
but Jupyter Notebooks still report "Problems" before the code is executed:
<img width="805" alt="Bildschirmfoto 2023-12-03 um 18 58 07" src="https://github.com/microsoft/vscode-jupyter/assets/6557139/2a02bc43-a0df-40ad-b796-559c973bea6c">
I think those "Problems" are reported not by Pylance (which is already disabled) but rather by the `ms-toolsai.jupyter` extension itself, could that be? How to turn that off?
