### ISSUE TITLE
result not showing

### ISSUE THREAD

**Issue by chenhao1umbc** [microsoft/vscode-jupyter#12454]
Type: <b>Bug</b>

it just randomly happend, I do not know how to reproduce it. It happened quite a lot of time, which is really annoying 

Extension version: 2022.11.1003412109
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 5.15.0-56-generic
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.4.0-235-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1319)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (9.27GB free)|
|Process Argv|--unity-launch --crash-reporter-id 890f7787-50ba-4207-9b29-fe529d42b4b5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: pensees|
|OS|Linux x64 4.4.0-235-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 2945)|
|Memory (System)|251.81GB (237.11GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by chenhao1umbc** [comment]
Please check out his screen shot
https://photos.app.goo.gl/3NMYBzMvcswtWJic9

**Comment by DonJayamanne** [comment]
Thanks for filing this issue
Please could you try clicking on the three `...` dots next to the output and swith the presentation if you have changed this.
see below screenshot.

![Screenshot 2022-12-29 at 10 43 00](https://user-images.githubusercontent.com/1948812/209885503-8d8bff79-606d-4c6d-881f-742324d7fa50.png)

If that doesn't work, then please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by chenhao1umbc** [comment]
Thanks for your reply. I never changed the presentation and it did not work. One more thing to mention, I have the `Interactive Window Mode` as `perfile`. I don't know it is related.

 I have  the logging to verbose, which was debug as the default. Also I have reloaded the VS code. If I encounter the problem again. I will come back here. Thanks.

**Comment by chenhao1umbc** [comment]
It happened again, but there was no error message or log popped up. This happened after I debug the cell.

![Screenshot from 2022-12-29 13-10-07](https://user-images.githubusercontent.com/25485451/209992686-3a50c3cf-3a88-45b9-b99f-f97454ec1604.png)

**Comment by DonJayamanne** [comment]
when you run into this issue please could you send the notebook (or a screenshot) as well as all the output from the logs as requested easier

**Comment by chenhao1umbc** [comment]
Sure, where can I find the logs?

**Comment by DonJayamanne** [comment]
please could you upload the logs from the `Jupyter` output panel, you can get there output using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.

**Comment by DrShushen** [comment]
Possibly related?

I've been having the problem (as of today) due to what I'm guessing is the renderer thinking there are HTML tags in the output, e.g.:

```pyton
# Cell content
print("<class 'int'>")
```
Output shows nothing.

(Something like `print("bla")` shows output just fine.)

Opening the same notebook in, say, jupyter lab shows the output for the above cell as normal - so only no output when in VSCode.

<details>
  <summary>Debug info</summary>

### System info
CPUs | Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 800)
-- | --
GPU Status | 2d_canvas: unavailable_software canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: disabled_software multiple_raster_threads: enabled_on opengl: disabled_off rasterization: disabled_software raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: unavailable_software webgl2: unavailable_software webgpu: disabled_off
Load (avg) | 1, 1, 1
Memory (System) | 62.71GB (54.44GB free)
Process Argv | --no-sandbox --force-user-env --unity-launch --crash-reporter-id 5e036db4-7975-4920-936d-345ce33b1cab
Screen Reader | no
VM | 0%

### Enabled extensions
Extension | Author (truncated) | Version
-- | -- | --
vscode-postgres | cko | 1.4.0
gitlens-insiders | eam | 2022.12.2304
language-cython | guy | 0.0.7
vscode-systemd-support | han | 1.0.1
vscode-edit-csv | jan | 0.7.2
vscode-docker | ms- | 1.23.3
isort | ms- | 2022.9.13271012
python | ms- | 2022.21.13601008
vscode-pylance | ms- | 2022.12.20
jupyter | ms- | 2023.1.1003651031
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.12
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-slideshow | ms- | 0.1.5
remote-containers | ms- | 0.269.0
remote-ssh | ms- | 0.94.0
remote-ssh-edit | ms- | 0.84.0
remote-wsl | ms- | 0.72.0
vscode-remote-extensionpack | ms- | 0.23.0
remote-explorer | ms- | 0.0.3
autodocstring | njp | 0.6.1
code-spell-checker | str | 2.12.0
even-better-toml | tam | 0.19.0
simple-rst | tro | 1.5.2
zoombar-vscode | wra | 1.4.2

### A/B experiments
```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30622696
fim-prod:30623723
```

### Just in case, my particular conda environment:
```yaml
name: py38
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.11.7
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - flake8=4.0.1
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - jupyterlab_widgets=1.0.0
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyflakes=2.4.0
  - pygments=2.11.2
  - pylint=2.14.5
  - pyopenssl=22.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.14.1
  - xz=5.2.8
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - black==22.12.0
      - chardet==5.1.0
      - click==8.1.3
      - colorama==0.4.6
      - commonmark==0.9.1
      - frictionless==4.40.8
      - isodate==0.6.1
      - marko==1.2.2
      - mypy==0.991
      - mypy-extensions==0.4.3
      - pandas-stubs==1.4.3.220807
      - pandera==0.13.4
      - pathspec==0.10.3
      - petl==1.7.12
      - pydantic==1.10.3
      - python-slugify==7.0.0
      - rfc3986==2.0.0
      - rich==12.6.0
      - shellingham==1.5.0
      - simpleeval==0.9.12
      - stringcase==1.2.0
      - tabulate==0.9.0
      - text-unidecode==1.3
      - tokenize-rt==5.0.0
      - typer==0.7.0
      - types-pytz==2022.7.0.0
      - typing-inspect==0.8.0
      - validators==0.20.0
```

</details>
