### ISSUE TITLE
Waiting for connection to be idle

### ISSUE THREAD

**Issue by jaymc-arg** [microsoft/vscode-jupyter#15852]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm connecting to a remote jupyterhub server and after log in I can not execute any cell because it keeps hanging with the notification: "Waiting for Jupyter session to be idle", and after some time "Connectinc to kernel: Ipython3". I've tryed to run the server locally, but the same issue appears.
I've used the extension with this same server in the past and it was working fine, I do also can reach the server with from my browser.
This is the docker-compose.yml i'm using to run the server:
```
version: "3"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: 4.0.0
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    ports:
      - "8000:8000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: caraboy/datascience-sintys:0.1.2 # personal datascience notebook with some ENV vars for oracle drivers and system package instalation (oracledb driver, wget, unzip, etc)
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      # log level
      LOG_LEVEL: DEBUG
volumes:
  jupyterhub-data:

networks:
 jupyterhub-network:
    name: jupyterhub-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  # SOME IP RANGE of my organization

```

### VS Code Version

1.90.2 5437499feb04f7a586f677b155b039bc2b3669eb x64

### Jupyter Extension Version

v2024.6.0

### Jupyter logs

Not sure on how i can get the logs, with `jupyter show output` but i've done it with `jupyter notebook --debug`

```shell

[D 2024-07-16 14:43:09.791 ServerApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /usr/etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /root/.local/etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /root/.jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /usr/etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /root/.local/etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /root/.jupyter
[D 2024-07-16 14:43:09.801 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.802 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyter-lsp-jupyter-server.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyter_server_terminals.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/notebook.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/notebook_shim.json
    	/usr/local/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.802 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.803 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/root/.local/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.803 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/root/.jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.810 ServerApp] Extension package notebook took 0.0000s to import
[D 2024-07-16 14:43:09.823 ServerApp] Extension package jupyter_lsp took 0.0120s to import
[D 2024-07-16 14:43:09.832 ServerApp] Extension package jupyter_server_terminals took 0.0081s to import
[D 2024-07-16 14:43:09.833 ServerApp] Extension package jupyterlab took 0.0000s to import
[D 2024-07-16 14:43:10.483 ServerApp] Paths used for configuration of page_config: 
    	/usr/etc/jupyter/labconfig/page_config.json
[D 2024-07-16 14:43:10.484 ServerApp] Paths used for configuration of page_config: 
    	
[D 2024-07-16 14:43:10.491 ServerApp] Extension package notebook_shim took 0.0000s to import
[I 2024-07-16 14:43:10.491 ServerApp] jupyter_lsp | extension was successfully linked.
[D 2024-07-16 14:43:10.496 TerminalsExtensionApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2024-07-16 14:43:10.497 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-07-16 14:43:10.498 ServerApp] jupyter_server_terminals | extension was successfully linked.
[D 2024-07-16 14:43:10.504 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-07-16 14:43:10.505 ServerApp] jupyterlab | extension was successfully linked.
[D 2024-07-16 14:43:10.510 JupyterNotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-07-16 14:43:10.511 ServerApp] notebook | extension was successfully linked.
[D 2024-07-16 14:43:10.819 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/root/.jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.819 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.819 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.820 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.820 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/root/.local/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.820 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/root/.jupyter/jupyter_notebook_config.json
[I 2024-07-16 14:43:10.820 ServerApp] notebook_shim | extension was successfully linked.
[D 2024-07-16 14:43:10.822 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}}
[I 2024-07-16 14:43:10.842 ServerApp] notebook_shim | extension was successfully loaded.
[D 2024-07-16 14:43:10.844 ServerApp] [lsp] rootUri will be file:///srv/jupyterhub
[D 2024-07-16 14:43:10.844 ServerApp] [lsp] virtualDocumentsUri will be file:///srv/jupyterhub/.virtual_documents
[I 2024-07-16 14:43:10.845 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-07-16 14:43:10.846 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-07-16 14:43:10.847 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 2024-07-16 14:43:10.847 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2024-07-16 14:43:10.848 LabApp] Extension Manager is 'pypi'.
[D 2024-07-16 14:43:10.848 LabApp] Plugins in PyPIExtensionManager will managed on the sys_prefix level
[D 2024-07-16 14:43:10.913 LabApp] Extensions list will be fetched from https://pypi.org/pypi.
[D 2024-07-16 14:43:10.914 LabApp] Plugins in PluginManager will managed on the sys_prefix level
[D 2024-07-16 14:43:10.915 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.915 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.916 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.916 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.916 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.jupyter/labconfig/default_setting_overrides.json
[I 2024-07-16 14:43:10.919 ServerApp] jupyterlab | extension was successfully loaded.
[D 2024-07-16 14:43:10.921 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.921 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.922 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.922 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.922 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.jupyter/labconfig/default_setting_overrides.json
[I 2024-07-16 14:43:10.923 ServerApp] notebook | extension was successfully loaded.
[C 2024-07-16 14:43:10.924 ServerApp] Running as root is not recommended. Use --allow-root to bypass.
[D 2024-07-16 14:43:10.924 ServerApp] Exiting application: jupyter-server
```

### Coding Language and Runtime Version

python 3.10

### Running Jupyter locally or remotely?

Remote
