### ISSUE TITLE
Notebook metadata being initialised in wrong place 

### ISSUE THREAD

**Issue by chrisjsewell** [microsoft/vscode-jupyter#2176]
# Bug: Notebook Editor, Interactive Window, Editor cells

First noted in  jupyter/jupyter-sphinx#108

Creating a new notebook with:

```yaml
Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.
Version: 2020.2.64397
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python 
```

leads to:

```json
{
 "nbformat": 4,
 "nbformat_minor": 2,
 "metadata": {
  "language_info": {
    "name": "python",
    "codemirror_mode": {
      "name": "ipython",
      "version": 3
   }
  },
  "orig_nbformat": 2,
  "file_extension": ".py",
  "mimetype": "text/x-python",
  "name": "python",
  "npconvert_exporter": "python",
  "pygments_lexer": "ipython3",
  "version": 3
 },
 "cells": []
}
```

This is incorrect, because all the metadata should actually be under the `language_info` key:

```json
{
 "nbformat": 4,
 "nbformat_minor": 2,
 "metadata": {
  "language_info": {
    "name": "python",
    "codemirror_mode": {
      "name": "ipython",
      "version": 3,
    },
    "orig_nbformat": 2,
    "file_extension": ".py",
    "mimetype": "text/x-python",
    "name": "python",
    "npconvert_exporter": "python",
    "pygments_lexer": "ipython3",
    "version": 3
  },
 },
 "cells": []
}
```
