### ISSUE TITLE
Variable explorer and data viewer do not match documentation / broken

### ISSUE THREAD

**Issue by pjgoodall** [microsoft/vscode-jupyter#2241]
# Bug: Notebook Editor, Interactive Window, Editor cells

```
Version: 1.43.0-insider
Commit: e6a45f4242ebddb7aa9a229f85555e8a3bd987e2
Date: 2020-02-21T05:40:52.685Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic snap
```

Steps to Reproduce:

1. Create conda environment from `environment.yml`
``` yml
name: Data-Cleaning
channels:
  - nodefaults
  - fastai
  - pytorch
dependencies:
  - anaconda::python=3.7
  - fastai::fastai
  - anaconda::pylint
  - anaconda::pip
  - anaconda::pandas
  - conda-forge::black
  - conda-forge::nb_black
  - anaconda::jupyterlab
  - anaconda::notebook
  - anaconda::nb_conda
  - anaconda::flake8
  - conda-forge::jupyter_contrib_nbextensions
```
2. Create/open jupyter notebook
``` ipynb
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Prepare TextNoText DataBunch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from fastai.vision import *\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext lab_black"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "from pathlib import PurePath as PP\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Directories\n",
    "baseDir = Path.cwd()\n",
    "dataDir = baseDir / \"Data\"\n",
    "imageDir = dataDir / \"Raw_Images\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Datafiles\n",
    "labelCSVPath = baseDir / \"TextNoTextLabels.csv\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!ls {imageDir} | head"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```
3. Execute some cells to populate variables. Open the Variable Explorer as described in [vs-code jupyter support > variable explorer](https://code.visualstudio.com/docs/python/jupyter-support#_variable-explorer-and-data-viewer). 

## Problem illustration
The Variable Explorer shows an overwhelming list of Jupyter Kernel Variables. It is impossible to find variables local to the notebook. Double-Click to open a *Data Viewer* does not work.

![vscode-VariableExplorer-Bug](https://user-images.githubusercontent.com/719962/75198627-39e18700-57b5-11ea-893a-fe2a4c47476f.png)

## Developer Tools Console Output
[Developer Tools Console Output.txt](https://github.com/microsoft/vscode-python/files/4247266/Developer.Tools.Console.Output.txt)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer
